### PR TITLE
Namespace sidebar-specific styles

### LINKED ISSUE #212: Footer is offset for all tablet-up screens
Saw this on our Pandemic EBT apps:

Apply_for_P-EBT__Pandemic_EBT_

View it live: https://ca-demo.p-ebt.org/en/

I think this issue popped up because of some recent sidebar work:

https://github.com/codeforamerica/honeycrisp-gem/blob/7430ee20b4535f73c46f47b62cf8f4d80698c0ce/app/assets/stylesheets/_sidebar-nav.scss#L171-L173

The `left: $sidebar-width` rule is being applied to all tablet-up instances of `.main-footer`, even in cases where the sidebar isn't present.

### PR DESCRIPTION
**Pull request by hartsick**
Previously some overrides were in the general CSS namespace, which
overrode the values in undesired places (without nav bar, not on
styleguide index). This instead scopes them to only appearing with
specific classes.

Also does some HTML restructuring and standardization of CSS names to
match BEM convention, removal of unused CSS selectors, reorganizing some
styles to be mobile first, and using media mixins rather than
constructing media queries.

Should close #212, though I still need to test in a host project. Could someone help with this?

**Also**:
Prevents exception when assets not precompiled. I was getting an exception when loading the styleguide documentation
after running `bin/rails s` in development because my assets weren't precompiled, which is expected in development. I'm not sure when this was introduced (below issue suggests 2016, so may have appeared once we upgraded Rails/Sprockets) or if others are running into it. **Can split this out into separate PR if it makes sense.**

Screen Shot 2021-01-26 at 6 53 21 PM
Screen Shot 2021-01-26 at 6 53 25 PM
Screen Shot 2021-01-26 at 6 53 28 PM
Screen Shot 2021-01-26 at 6 53 30 PM

### CODE REVIEW

**Comment by ash-rc** [comment]
@hartsick I can help with testing in GCF if you need it!

**Comment by hartsick** [comment]
@ash-rc that'd be great! let me know if you need any help testing it out. I mainly want to just verify that it does indeed solve the problem

**Review by ash-rc — APPROVED** [review]
This looks great! Tested it out on a PR branch in GCF, https://getcalfresh-percy-updat-gtjian.herokuapp.com/

With and without the sidebar, the footer has the right left alignment. I also really like the renaming here. 

Without sidebar: 
without_sidebar

With sidebar:
with_sidebar

**Comment by hartsick** [comment]
@ash-rc Great, thank you! Especially for sharing that review link, super handy. Going to merge this in.

**Pull request merged**
