### PR TITLE
Add tabs to code examples for different languages (html, erb)

### PR DESCRIPTION
**Pull request by jenny-heath**

### CODE REVIEW

**Comment by jenny-heath** [comment]
it's not very pretty yet but it works i think

image
image

**Comment by hartsick** [comment]
@jenny-heath This is looking great so far! 🎉 

Would you mind marking it as a "Draft" or with "WIP" in front of the title while you're continuing to work on it? Will help us keep track of what's ready for review/merging.

**Comment by jenny-heath** [comment]
nicer now
image

**Comment by mrotondo** [comment]
Resolves #121

**Pull request merged**
